# Generated by Django 3.0.8 on 2020-08-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='project',
            name='tags',
            field=models.CharField(default='all', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
