# Generated by Django 3.0.8 on 2020-08-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('tags', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=400)),
                ('link', models.CharField(max_length=100)),
            ],
        ),
    ]
