# Generated by Django 3.0.8 on 2020-08-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_certificates'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificates',
            name='image',
            field=models.ImageField(default='#', upload_to='images/projects/'),
        ),
    ]
