# Generated by Django 3.0.8 on 2020-08-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_certificates_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='image',
            field=models.ImageField(default='#', upload_to='images/certificates/'),
        ),
    ]
